<a href="https://colab.research.google.com/github/begoon/colab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [11]:
gs = 5

In [98]:
a = np.array(range(gs * gs)).reshape(gs, gs)
print(a)
print(a[0])
print(a[0][::-1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[0 1 2 3 4]
[4 3 2 1 0]


In [165]:
shapes = [
  # shape,             value,  stop, combo
  [[1, 1, 1, 1, 1   ], 500000, 1,    0],     # "XXXXX"
  [[0, 1, 1, 1, 1, 0], 500000, 1,    0],     # " XXXX "
  [[1, 1, 1, 1, 1, 0],   1000, 0,    1],     # "XXXX "   XXX X

  # OXXX  XXXO
  # OXXX xXX XO
  # ^^^^^
  #     ^^^^^ 

  [[1, 0, 0, 0, 0], 1, 1, 0],        # "X    "  S
  [[1, 1, 0, 0, 0], 2, 1, 0],        # "XX   "  S
  [[1, 1, 1, 0, 0], 3, 1, 0],        # "XXX  "  S
  [[1, 1, 1, 1, 0], 1000, 1, 1],     # "XXXX "  S, WC
  [[0, 1, 0, 0, 0], 1, 1, 0],        # " X   "  S
  [[0, 0, 1, 0, 0], 1, 0, 0],        # "  X  "
  [[0, 1, 1, 0, 0], 2, 1, 0],        # " XX  "  S
  [[0, 1, 1, 1, 0], 1000, 0, 1],     # " XXX "  -, WC
  [[1, 1, 1, 0, 1], 1000, 1, 1],     # "XXX X"  S, WC
  [[1, 1, 0, 1, 1], 1000, 1, 1],     # "XX XX"  -, WC
  [[1, 1, 0, 1, 1, 1], 1000, 1, 1],  # "XX XXX" S, WC
]
def find_shape(v, shape):
  shape_sz = len(shape)
  positions = []
  found = 0
  for i in range(len(v) - shape_sz + 1):
    if v[i:i + shape_sz] == shape:
       found += 1
       positions.append(i)
  return found, positions

def value_shapes(original_v, shapes):
  total_value = 0
  win_combos = 0
  for i, (shape, value, reverse, win_combo) in enumerate(shapes):
    v = list(original_v)
    found, positions = find_shape(v, shape)
    if found:
      print(found, positions, shape, value)
      total_value += found * value
      for j in positions:
        v[j:j+len(shape)] = [-1] * len(shape)
      if win_combo:
        win_combos += 1
    if reverse:
      found, positions = find_shape(v, shape[::-1])
      if found:
        print(found, positions, shape, value)
        total_value += found * value
      if win_combo:
        win_combos += 1
    if win_combos > 1:
      total_value += 10000
  return total_value

line = [0, 1, 1, 1, 0, 1, 1, 1, 0] ???
print(value_shapes(line, shapes))

2 [0, 4] [0, 1, 1, 1, 0] 1000
1 [1] [1, 1, 1, 0, 1] 1000
1 [2] [1, 1, 0, 1, 1] 1000
1 [2] [1, 1, 0, 1, 1, 1] 1000
55000


In [84]:
def diagonals(f, x, y):
  ds = []
  ds.append(f.diagonal(x - y))
  ds.append(f[:, ::-1].diagonal((gs - x -1) - y))
  ds.append(f[:, y])
  ds.append(f[x, :])
  return ds
print(a)
print(diagonals(a, 2, 2))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[array([ 0,  6, 12, 18, 24]), array([ 4,  8, 12, 16, 20]), array([ 2,  7, 12, 17, 22]), array([10, 11, 12, 13, 14])]
111
